### ISSUE TITLE
Blank screen on login after server upgrade.

The blank screen was caused by a value in the app confi

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#715]
Blank screen on login after server upgrade.

The blank screen was caused by a value in the app configuration being set after it was used due to promise resolution issues in our configuration before the app is bootstrapped.

Now fixed and verified as fixed by developer who can reproduce reliably locally.

 Karen Porter: must be served over HTTPS.send @ vendor.49968763.js:12
vendor.49968763.js:7 Error: [$injector:unpr] Unknown provider: skinConfigProvider <- skinConfig
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=skinConfigProvider%20%3C-<div id="show-everything-here" ui-view="" class="ng-scope">kinConfig
    at https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:5:26896
    at https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12856
    at Object.d [as get] (https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12026)
    at https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12953
    at d (https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12026)
    at e (https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12363)
    at Object.f [as instantiate] (https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:12488)
    at https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:7:1270
    at https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:52:7179
    at fa (https://chembiohub.ox.ac.uk/hub/scripts/vendor.49968763.js:6:30153)(anonymous function) @ vendor.49968763.js:7
https://chembiohub.ox.ac.uk/hub/styles/bootstrap.css Failed to load resource: the server responded with a status of 404 (Not Found)
[13:00:11] Andrew Stretton: yes this is the same thing
[13:01:06] Andrew Stretton: I will take a quick look to see if there is anything obvious

**Comment by strets123** [comment]
now fixed on hub
